Try a custom script to verify definiteAssignment works as expected

diff --git a/.github/workflows/msbuild.yml b/.github/workflows/msbuild.yml
--- a/.github/workflows/msbuild.yml
+++ b/.github/workflows/msbuild.yml
@@ -59,6 +59,13 @@ jobs:
       - name: Test VerifyDafny task (sequential)
         run: dotnet build dafny.msbuild/Test -t:VerifyDafny -p:VerifyDafnyJobs=1
       - name: Test VerifyDafny task (sequential with definite assignment)
-        run: dotnet build dafny.msbuild/Test -t:VerifyDafny -p:VerifyDafnyJobs=1 -p:VerifyTestProjectOverride="definiteAssignment:3"
+        run:
+          if (dotnet build dafny.msbuild/Test -t:VerifyDafny -p:VerifyDafnyJobs=1 -p:VerifyTestProjectOverride="definiteAssignment:3") | grep -q 'Build FAILED.'; then
+            echo "This failed, as it should have given the definiteAssignment flag"
+            exit 0
+          else
+            echo "This succeeded when it shouldn't have"
+            exit 1
+          fi
       - name: Run tests on TestProject
         run: dotnet test dafny.msbuild/Test
