feat!: Make VerifyDafny take a list of params (#11)
Switched the verify task to take in a list of arguments (user defined) instead of pre-determined options. This allows the verify task to support new options like definiteAssignment without having to specifically add it.

diff --git a/.github/workflows/msbuild.yml b/.github/workflows/msbuild.yml
--- a/.github/workflows/msbuild.yml
+++ b/.github/workflows/msbuild.yml
@@ -58,5 +58,14 @@ jobs:
         run: dotnet build dafny.msbuild/Test -t:VerifyDafny
       - name: Test VerifyDafny task (sequential)
         run: dotnet build dafny.msbuild/Test -t:VerifyDafny -p:VerifyDafnyJobs=1
+      - name: Test VerifyDafny task (sequential with definite assignment)
+        run: |
+          if (dotnet build dafny.msbuild/Test -t:VerifyDafny -p:VerifyDafnyJobs=1 -p:VerifyTestProjectOverride="definiteAssignment:3") | grep -q 'Build FAILED.'; then
+            echo "Failed as expected because the definiteAssignment flag was provided to Dafny with a value of 3"
+            exit 0
+          else
+            echo "This succeeded when it shouldn't have"
+            exit 1
+          fi
       - name: Run tests on TestProject
         run: dotnet test dafny.msbuild/Test
